---
server:
  error:
    include-stacktrace: never
  port: 5555

spring:
  main:
    banner-mode: off
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: security
          uri: https://s10-14-ft-api-security.azurewebsites.net
          #uri: lb://security
          predicates:
            - Path=/**

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: https://s10-14-ft-eurekaserver.azurewebsites.net/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

#security:
  #service:
    #url: http://localhost:8081
...